//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.26 at 10:05:24 AM AST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://kng.kw/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kw.kng.courses;
